com.ucoruh.password.PasswordManager Class Reference
Main class for the Password Manager application.
Classes
class PendingOperationsQueue
Custom Queue implementation using linked nodes.
class ServiceGraph
Graph data structure for tracking service dependencies.
Public Member Functions
PasswordManager (String masterPassword)
Constructor initializing the manager with a master password.
PasswordManager (String masterPassword, StorageType storageType)
Constructor with specified storage type.
void addCredential (String account, String password)
Adds a new credential.
String getCredential (String account)
Retrieves a credential.
Map< Integer, Integer > getAccessPattern (String service)
Gets access pattern for a specific service.
List< String > getMostAccessedServices (int topN)
Gets the most accessed services.
int getTotalAccessCount (String service)
Gets total access count for a service.
boolean undo ()
Undoes the last operation.
boolean redo ()
Redoes the last undone operation.
boolean canUndo ()
Checks if undo is available.
boolean canRedo ()
Checks if redo is available.
void menu (Scanner scanner, PrintStream out)
Displays the interactive menu and processes user input.
List< String > getMostUsedServicesByHeapSort ()
Gets most used services sorted by usage count using heap sort.
List< String > getRelatedServices (String service)
Analyzes service dependencies and returns related services.
void addServiceDependency (String service1, String service2)
Adds a dependency relationship between two services.
List< List< String > > getServiceClusters ()
Gets all strongly connected components in service dependencies.
ServiceGraph getServiceGraph ()
Gets the service dependency graph.
void queueOperation (String operation)
Queues a pending operation.
List< String > processPendingOperations ()
Processes all pending operations.
int getPendingOperationsCount ()
Gets the count of pending operations.
String peekNextOperation ()
Peeks at the next pending operation without removing it.
PendingOperationsQueue getOperationsQueue ()
Gets the pending operations queue.
Static Public Member Functions
static void runApp (Scanner scanner, PrintStream out)
Runs the application using the provided Scanner and PrintStream.
static void main (String[] args)
Main method to launch the console application.
Detailed Description
Main class for the Password Manager application.
Definition at line 34 of file PasswordManager.java.
Constructor & Destructor Documentation
PasswordManager() [1/2]
com.ucoruh.password.PasswordManager.PasswordManager (String masterPassword)
Constructor initializing the manager with a master password.
Initializes the credentials map and loads stored credentials.
Parameters
masterPassword Master password used for encryption/decryption.
Definition at line 86 of file PasswordManager.java.
                                                {
    this.masterPassword = masterPassword;
    this.credentials = new CustomHashTable<>();
    this.storage = PasswordStorageFactory.create(StorageType.FILE, masterPassword);
    this.accessMatrix = new AccessMatrix();
    this.undoStack = new CommandStack();
    this.redoStack = new CommandStack();
    this.serviceGraph = new ServiceGraph();
    this.operationsQueue = new PendingOperationsQueue();
    loadCredentials();
  }
References com.ucoruh.password.PasswordStorageFactory.create(), and com.ucoruh.password.StorageType.FILE.
PasswordManager() [2/2]
com.ucoruh.password.PasswordManager.PasswordManager (String masterPassword, StorageType storageType)
Constructor with specified storage type.
Parameters
masterPassword Master password used for encryption/decryption.
storageType The type of storage to use.
Definition at line 104 of file PasswordManager.java.
                                                                         {
    this.masterPassword = masterPassword;
    this.credentials = new CustomHashTable<>();
    this.storage = PasswordStorageFactory.create(storageType, masterPassword);
    this.accessMatrix = new AccessMatrix();
    this.undoStack = new CommandStack();
    this.redoStack = new CommandStack();
    this.serviceGraph = new ServiceGraph();
    this.operationsQueue = new PendingOperationsQueue();
    loadCredentials();
  }
References com.ucoruh.password.PasswordStorageFactory.create().
Member Function Documentation
addCredential()
void com.ucoruh.password.PasswordManager.addCredential (String account, String password)
Adds a new credential.
Inserts the credential for the given account into the internal storage and saves it.
Parameters
account Account name.
password Password for the account.
Definition at line 136 of file PasswordManager.java.
                                                             {
    // Get old password for undo
    String oldPassword = credentials.get(account);
    credentials.put(account, password);
    // Create a password list and save it
    List<Password> passwordList = storage.readAll();
    boolean updated = false;
    // Check if the account already exists
    for (Password p : passwordList) {
      if (p.getService().equalsIgnoreCase(account)) {
        p.setPassword(password);
        updated = true;
        break;
      }
    }
    // If not found, add new entry
    if (!updated) {
      passwordList.add(new Password(account, "default_user", password));
    }
    storage.writeAll(passwordList);
    // Add command to undo stack
    if (oldPassword == null) {
      // New credential - undo should delete it
      undoStack.push(new AddCredentialCommand(account, password));
    } else {
      // Update credential - undo should restore old password
      undoStack.push(new UpdateCredentialCommand(account, oldPassword, password));
    }
    // Clear redo stack on new action
    redoStack.clear();
  }
References com.ucoruh.password.InterfacePasswordStorage.readAll(), and com.ucoruh.password.InterfacePasswordStorage.writeAll().
addServiceDependency()
void com.ucoruh.password.PasswordManager.addServiceDependency (String service1, String service2)
Adds a dependency relationship between two services.
Parameters
service1 Source service
service2 Dependent service
Definition at line 1464 of file PasswordManager.java.
                                                                     {
    serviceGraph.addEdge(service1, service2);
  }
canRedo()
boolean com.ucoruh.password.PasswordManager.canRedo ()
Checks if redo is available.
Returns
true if there are operations to redo
Definition at line 277 of file PasswordManager.java.
                           {
    return !redoStack.isEmpty();
  }
canUndo()
boolean com.ucoruh.password.PasswordManager.canUndo ()
Checks if undo is available.
Returns
true if there are operations to undo
Definition at line 268 of file PasswordManager.java.
                           {
    return !undoStack.isEmpty();
  }
getAccessPattern()
Map< Integer, Integer > com.ucoruh.password.PasswordManager.getAccessPattern (String service)
Gets access pattern for a specific service.
Parameters
service Service name
Returns
Map of hour to access count
Definition at line 205 of file PasswordManager.java.
                                                                {
    return accessMatrix.getAccessPattern(service);
  }
getCredential()
String com.ucoruh.password.PasswordManager.getCredential (String account)
Retrieves a credential.
Fetches the password associated with the specified account.
Parameters
account Account name.
Returns
Password if account exists; otherwise, returns null.
Definition at line 181 of file PasswordManager.java.
                                              {
    // Reload credentials to ensure we have the latest
    loadCredentials();
    // Record access in matrix
    recordServiceAccess(account);
    return credentials.get(account);
  }
Referenced by com.ucoruh.password.AutoLoginManager.autoLogin().
getMostAccessedServices()
List< String > com.ucoruh.password.PasswordManager.getMostAccessedServices (int topN)
Gets the most accessed services.
Parameters
topN Number of top services to return
Returns
List of service names sorted by access count
Definition at line 215 of file PasswordManager.java.
                                                        {
    return accessMatrix.getMostAccessedServices(topN);
  }
getMostUsedServicesByHeapSort()
List< String > com.ucoruh.password.PasswordManager.getMostUsedServicesByHeapSort ()
Gets most used services sorted by usage count using heap sort.
Combines access matrix data with heap sort for efficient ranking.
Returns
List of services sorted by usage count
Definition at line 976 of file PasswordManager.java.
                                                      {
    List<String> services = accessMatrix.getAllServices();
    if (services.isEmpty()) {
      return new ArrayList<>();
    }
    // Create array of service usage
    ServiceUsage[] usageArray = new ServiceUsage[services.size()];
    for (int i = 0; i < services.size(); i++) {
      String service = services.get(i);
      int count = accessMatrix.getTotalAccessCount(service);
      usageArray[i] = new ServiceUsage(service, count);
    }
    // Sort using heap sort (ascending)
    heapSort(usageArray);
    // Reverse to get descending order (most used first)
    List<String> result = new ArrayList<>();
    for (int i = usageArray.length - 1; i >= 0; i--) {
      ServiceUsage usage = usageArray[i];
      result.add(usage.getService() + " (" + usage.getUsageCount() + " accesses)");
    }
    return result;
  }
getOperationsQueue()
PendingOperationsQueue com.ucoruh.password.PasswordManager.getOperationsQueue ()
Gets the pending operations queue.
Returns
PendingOperationsQueue instance
Definition at line 1533 of file PasswordManager.java.
                                                     {
    return operationsQueue;
  }
getPendingOperationsCount()
int com.ucoruh.password.PasswordManager.getPendingOperationsCount ()
Gets the count of pending operations.
Returns
Number of pending operations
Definition at line 1515 of file PasswordManager.java.
                                         {
    return operationsQueue.size();
  }
getRelatedServices()
List< String > com.ucoruh.password.PasswordManager.getRelatedServices (String service)
Analyzes service dependencies and returns related services.
Uses BFS to find all services reachable from the given service.
Parameters
service Service name
Returns
List of related services
Definition at line 1454 of file PasswordManager.java.
                                                         {
    return serviceGraph.bfs(service);
  }
getServiceClusters()
List< List< String > > com.ucoruh.password.PasswordManager.getServiceClusters ()
Gets all strongly connected components in service dependencies.
Returns
List of SCCs
Definition at line 1473 of file PasswordManager.java.
                                                 {
    return serviceGraph.findStronglyConnectedComponents();
  }
getServiceGraph()
ServiceGraph com.ucoruh.password.PasswordManager.getServiceGraph ()
Gets the service dependency graph.
Returns
ServiceGraph instance
Definition at line 1482 of file PasswordManager.java.
                                        {
    return serviceGraph;
  }
getTotalAccessCount()
int com.ucoruh.password.PasswordManager.getTotalAccessCount (String service)
Gets total access count for a service.
Parameters
service Service name
Returns
Total number of accesses
Definition at line 225 of file PasswordManager.java.
                                                 {
    return accessMatrix.getTotalAccessCount(service);
  }
main()
static void com.ucoruh.password.PasswordManager.main (String[] args) [static]
Main method to launch the console application.
Entry point of the application. Initializes input and output streams, then invokes the runApp method.
Parameters
args Command-line arguments.
Definition at line 418 of file PasswordManager.java.
                                         {
    Scanner scanner = new Scanner(System.in);
    runApp(scanner, System.out);
    scanner.close();
  }
References com.ucoruh.password.PasswordManager.runApp().
menu()
void com.ucoruh.password.PasswordManager.menu (Scanner scanner, PrintStream out)
Displays the interactive menu and processes user input.
Uses dependency injection for Scanner and PrintStream to enable unit testing. Provides options to add, retrieve credentials, generate passwords, or exit.
Parameters
scanner The Scanner object for reading user input.
out The PrintStream object for writing output.
Definition at line 290 of file PasswordManager.java.
                                                     {
    boolean back = false;
    while (!back) {
      out.println("\n==== PASSWORD STORAGE MENU ====");
      out.println("1. Add New Password");
      out.println("2. View All Passwords");
      out.println("3. Update Password");
      out.println("4. Delete Password");
      out.println("5. Generate and Save Password");
      out.println("0. Back to Main Menu");
      out.print("Your choice: ");
      String input = scanner.nextLine();
      try {
        int choice = Integer.parseInt(input);
        switch (choice) {
          case 1:
            storage.add(scanner);
            break;
          case 2:
            storage.view();
            break;
          case 3:
            storage.update(scanner);
            break;
          case 4:
            storage.delete(scanner);
            break;
          case 5:
            generateAndSavePassword(scanner, out);
            break;
          case 0:
            back = true;
            break;
          default:
            out.println("Invalid choice.");
            break;
        }
        // Reload credentials after operations
        loadCredentials();
      } catch (NumberFormatException e) {
        out.println("Invalid number.");
      }
    }
  }
References com.ucoruh.password.InterfacePasswordStorage.add(), com.ucoruh.password.InterfacePasswordStorage.delete(), com.ucoruh.password.InterfacePasswordStorage.update(), and com.ucoruh.password.InterfacePasswordStorage.view().
Referenced by com.ucoruh.password.PasswordApp.runApp(), and com.ucoruh.password.PasswordManager.runApp().
peekNextOperation()
String com.ucoruh.password.PasswordManager.peekNextOperation ()
Peeks at the next pending operation without removing it.
Returns
Next operation or null if queue is empty
Definition at line 1524 of file PasswordManager.java.
                                    {
    return operationsQueue.peek();
  }
processPendingOperations()
List< String > com.ucoruh.password.PasswordManager.processPendingOperations ()
Processes all pending operations.
Returns
List of processed operations
Definition at line 1500 of file PasswordManager.java.
                                                 {
    List<String> processed = new ArrayList<>();
    while (!operationsQueue.isEmpty()) {
      processed.add(operationsQueue.dequeue());
    }
    return processed;
  }
queueOperation()
void com.ucoruh.password.PasswordManager.queueOperation (String operation)
Queues a pending operation.
Parameters
operation Operation description
Definition at line 1491 of file PasswordManager.java.
                                               {
    operationsQueue.enqueue(operation);
  }
redo()
boolean com.ucoruh.password.PasswordManager.redo ()
Redoes the last undone operation.
Returns
true if redo was successful, false if nothing to redo
Definition at line 252 of file PasswordManager.java.
                        {
    if (redoStack.isEmpty()) {
      return false;
    }
    Command cmd = redoStack.pop();
    cmd.execute();
    undoStack.push(cmd);
    return true;
  }
runApp()
static void com.ucoruh.password.PasswordManager.runApp (Scanner scanner, PrintStream out) [static]
Runs the application using the provided Scanner and PrintStream.
Initiates the application by requesting the master password and then invoking the interactive menu.
Parameters
scanner Scanner for user input.
out PrintStream for output.
Definition at line 403 of file PasswordManager.java.
                                                              {
    out.print("Enter master password: ");
    String masterPwd = scanner.nextLine();
    PasswordManager pm = new PasswordManager(masterPwd);
    pm.menu(scanner, out);
  }
References com.ucoruh.password.PasswordManager.menu().
Referenced by com.ucoruh.password.PasswordManager.main().
undo()
boolean com.ucoruh.password.PasswordManager.undo ()
Undoes the last operation.
Returns
true if undo was successful, false if nothing to undo
Definition at line 236 of file PasswordManager.java.
                        {
    if (undoStack.isEmpty()) {
      return false;
    }
    Command cmd = undoStack.pop();
    cmd.undo();
    redoStack.push(cmd);
    return true;
  }
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/PasswordManager.java