com.ucoruh.password.gui.PasswordManagerGUI Class Reference
Main graphical user interface for the Password Manager application.
Public Member Functions
PasswordManagerGUI ()
Constructor for the PasswordManagerGUI.
JButton createStyledButton (String text, Color bgColor)
Creates a styled button with consistent appearance.
Static Public Member Functions
static void main (String[] args)
Application entry point.
Static Public Attributes
static final Color PRIMARY_COLOR = new Color(26, 115, 232)
Color constants for the modern UI theme.
static final Color SECONDARY_COLOR = new Color(52, 168, 83)
Secondary color used in the GUI (Google Green)
static final Color ACCENT_COLOR = new Color(234, 67, 53)
Accent color used in the GUI (Google Red)
static final Color DARK_COLOR = new Color(66, 66, 66)
Dark color used in the GUI (Dark gray)
static final Color LIGHT_COLOR = new Color(245, 245, 245)
Light color used in the GUI (Light gray)
static final Color TEXT_COLOR = new Color(33, 33, 33)
Text color used in the GUI.
static final Color HEADER_BG = new Color(33, 33, 33)
Header background color used in the GUI.
Detailed Description
Main graphical user interface for the Password Manager application.
Provides a user-friendly interface for managing passwords, including features like password generation, storage, and auto-login capabilities.
Definition at line 25 of file PasswordManagerGUI.java.
Constructor & Destructor Documentation
PasswordManagerGUI()
com.ucoruh.password.gui.PasswordManagerGUI.PasswordManagerGUI ()
Constructor for the PasswordManagerGUI.
Initializes the main window, sets up controllers, and creates the UI components
Definition at line 171 of file PasswordManagerGUI.java.
                                {
        setTitle("Password Manager");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, 900, 650);
        setMinimumSize(new Dimension(900, 650));
        
        // Initialize Authentication Manager
        authManager = AuthManager.getInstance();
        
        // Initialize controllers
        initializeControllers();
        
        createComponents();
        
        // Clean up resources when window is closed
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // PasswordManager doesn't have an explicit savePasswords() method,
                // passwords are saved only when changed
                System.out.println("Application closing...");
            }
        });
        
        // Center on screen
        setLocationRelativeTo(null);
    }
References com.ucoruh.password.AuthManager.getInstance().
Referenced by com.ucoruh.password.gui.PasswordManagerGUI.main().
Member Function Documentation
createStyledButton()
JButton com.ucoruh.password.gui.PasswordManagerGUI.createStyledButton (String text, Color bgColor)
Creates a styled button with consistent appearance.
Creates a button with modern styling, hover effects, and consistent colors
Parameters
text The button text
bgColor The background color for the button
Returns
JButton The styled button instance
Definition at line 369 of file PasswordManagerGUI.java.
                                                                  {
        JButton button = new JButton(text);
        button.setForeground(Color.WHITE);
        button.setBackground(bgColor);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setFont(new Font("Segoe UI", Font.BOLD, 16));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setMargin(new Insets(10, 15, 10, 15));
        
        // Hover effect
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(darken(bgColor, 0.1f));
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(bgColor);
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
                button.setBackground(darken(bgColor, 0.2f));
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
                button.setBackground(darken(bgColor, 0.1f));
            }
        });
        
        return button;
    }
main()
static void com.ucoruh.password.gui.PasswordManagerGUI.main (String[] args) [static]
Application entry point.
Initializes the GUI with system look and feel and custom styling
Parameters
args Command line arguments (not used)
Definition at line 131 of file PasswordManagerGUI.java.
                                           {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            // Global style settings for Swing components
            UIManager.put("Button.arc", 8);
            UIManager.put("Component.arc", 8);
            UIManager.put("ProgressBar.arc", 8);
            UIManager.put("TextComponent.arc", 8);
            
            // Font settings
            Font defaultFont = new Font("Segoe UI", Font.PLAIN, 14);
            UIManager.put("Button.font", defaultFont);
            UIManager.put("Label.font", defaultFont);
            UIManager.put("TextField.font", defaultFont);
            UIManager.put("PasswordField.font", defaultFont);
            UIManager.put("TextArea.font", defaultFont);
            UIManager.put("ComboBox.font", defaultFont);
            UIManager.put("CheckBox.font", defaultFont);
            UIManager.put("RadioButton.font", defaultFont);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    PasswordManagerGUI frame = new PasswordManagerGUI();
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
References com.ucoruh.password.gui.PasswordManagerGUI.PasswordManagerGUI().
Member Data Documentation
ACCENT_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.ACCENT_COLOR = new Color(234, 67, 53) [static]
Accent color used in the GUI (Google Red)
Parameters
r Red component value: 234
g Green component value: 67
b Blue component value: 53
Definition at line 95 of file PasswordManagerGUI.java.
DARK_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.DARK_COLOR = new Color(66, 66, 66) [static]
Dark color used in the GUI (Dark gray)
Parameters
r Red component value: 66
g Green component value: 66
b Blue component value: 66
Definition at line 102 of file PasswordManagerGUI.java.
HEADER_BG
final Color com.ucoruh.password.gui.PasswordManagerGUI.HEADER_BG = new Color(33, 33, 33) [static]
Header background color used in the GUI.
Parameters
r Red component value: 33
g Green component value: 33
b Blue component value: 33
Definition at line 123 of file PasswordManagerGUI.java.
LIGHT_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.LIGHT_COLOR = new Color(245, 245, 245) [static]
Light color used in the GUI (Light gray)
Parameters
r Red component value: 245
g Green component value: 245
b Blue component value: 245
Definition at line 109 of file PasswordManagerGUI.java.
PRIMARY_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.PRIMARY_COLOR = new Color(26, 115, 232) [static]
Color constants for the modern UI theme.
Primary color used in the GUI (Google Blue)
Parameters
r Red component value: 26
g Green component value: 115
b Blue component value: 232
Definition at line 81 of file PasswordManagerGUI.java.
SECONDARY_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.SECONDARY_COLOR = new Color(52, 168, 83) [static]
Secondary color used in the GUI (Google Green)
Parameters
r Red component value: 52
g Green component value: 168
b Blue component value: 83
Definition at line 88 of file PasswordManagerGUI.java.
TEXT_COLOR
final Color com.ucoruh.password.gui.PasswordManagerGUI.TEXT_COLOR = new Color(33, 33, 33) [static]
Text color used in the GUI.
Parameters
r Red component value: 33
g Green component value: 33
b Blue component value: 33
Definition at line 116 of file PasswordManagerGUI.java.
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/gui/PasswordManagerGUI.java