com.ucoruh.password.InterfacePasswordStorage Interface Reference
Interface for password storage operations.
Public Member Functions
void add (Scanner scanner)
Adds a new password entry.
void view ()
Displays all saved password entries.
void update (Scanner scanner)
Updates an existing password entry.
void delete (Scanner scanner)
Deletes a password entry.
List< Password > readAll ()
Reads all saved password entries.
void writeAll (List< Password > list)
Writes all password entries to the storage.
Detailed Description
Interface for password storage operations.
Definition at line 20 of file InterfacePasswordStorage.java.
Member Function Documentation
add()
void com.ucoruh.password.InterfacePasswordStorage.add (Scanner scanner)
Adds a new password entry.
This method reads input from the user using the provided Scanner and adds a new password entry.
Parameters
scanner Scanner for user input.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.menu().
delete()
void com.ucoruh.password.InterfacePasswordStorage.delete (Scanner scanner)
Deletes a password entry.
This method deletes a password entry based on user input obtained via the provided Scanner.
Parameters
scanner Scanner for user input.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.menu().
readAll()
List< Password > com.ucoruh.password.InterfacePasswordStorage.readAll ()
Reads all saved password entries.
Retrieves all saved password entries from the underlying storage.
Returns
A list of Password entries.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.addCredential().
update()
void com.ucoruh.password.InterfacePasswordStorage.update (Scanner scanner)
Updates an existing password entry.
This method allows the user to update an existing password entry by specifying new details.
Parameters
scanner Scanner for user input.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.menu().
view()
void com.ucoruh.password.InterfacePasswordStorage.view ()
Displays all saved password entries.
This method retrieves and displays all password entries stored in the system.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.menu().
writeAll()
void com.ucoruh.password.InterfacePasswordStorage.writeAll (List< Password > list)
Writes all password entries to the storage.
This method writes the provided list of password entries to the underlying storage, replacing any existing entries.
Parameters
list List of Password entries.
Implemented in com.ucoruh.password.DatabasePasswordStorage, and com.ucoruh.password.FilePasswordStorage.
Referenced by com.ucoruh.password.PasswordManager.addCredential().
The documentation for this interface was generated from the following file:
password-app/src/main/java/com/ucoruh/password/InterfacePasswordStorage.java